### ISSUE TITLE
Connection.pm code review

### ISSUE THREAD

**Issue by pedros** [chcat/hbase-client#1]
Here's the Connection class hierarchy, as far as I can make it:

    HBase::Client::Connection::State
      HBase::Client::Connection::Disconnected
        HBase::Client::Connection::Opened
        HBase::Client::Connection::Closed
      HBase::Client::Connection::Disconnected    
      HBase::Client::Connection::Connecting

However, HBase::Client::Connection::State _requires__ its own subclasses:

    require HBase::Client::Connection::Opened;
    require HBase::Client::Connection::Connecting;
    require HBase::Client::Connection::Connected;
    require HBase::Client::Connection::Disconnected;
    require HBase::Client::Connection::Closed;

It's not clear why you do this. Even if weird side-effects do not
become immediately apparent, this reeks of an anti-pattern, and
suggests refactoring.

At the very least, specific implementations of, say, `State->close'
should be done at the subclass level, as appropriate. For example,
make either make `State->close' abstract, and let subclasses
determine the appropriate 'closed' state:

    sub close {
        my ($self, $state) = @_;

        croak 'Abstract method error'
            if $self->isa('HBase::Client::Connection::State');

        $self->_state($state);
    }

or, perhaps more appropriately, just drop the SUPER close, and
make_state publicly available:

    sub transition { shift->_state(shift); }

and create a new `Opened->close' method:

    sub close {
        my ($self) = @_;

        # either
        $self->SUPER::close($state);
        # or
        $self->transition($state);

        for my $write ( @{$self->{write_queue}} ) {
            $write->{callback}->( 'Connection closed' );
        }

        $self->{write_queue} = [];
    }

Also, and this might be related, you seem to be defining a state
machine implicitly, by having ad-hoc state transition methods (and
classes, in the case of `Connecting') that hard-code the new
states. why not make it explicit?

**Comment by chcat** [comment]
Indeed, it is a bit messy... The only reason State currently "requires" its subclasses is class loading: at the moment of a state change (like Disconnected->Connecting->Connected->Disconnected) the corresponding package should be loaded.

> At the very least, specific implementations of, say,`State->close` should be done at the subclass level, as appropriate. For example, make either make `State->close` abstract, and let subclasses
> determine the appropriate 'closed' state...

> At the very least, specific implementations of, say, State->close' should be done at the subclass level, as appropriate. For example, make either makeState->close' abstract, and let subclasses
> determine the appropriate 'closed' state

Indeed each state may react differently on `$connection->close(...)` call but is there a real reason to having multiple 'closed' states?

> ... or, perhaps more appropriately, just drop the SUPER close, and
> make_state publicly available

I think `_state` is too powerful method to be public: one can break a connection and leak a socket making arbitrary state transition.

After thinking on your comment I consider it was a mistake to combine _state holder_ and _state_ classes. Better would be to keep Connection as a class that keeps the socket, the state, and the writing queue as private fields and defines a set of reactions (on method calls and events from the socket), where part of the reaction logic is delegated to the state instance.

In this design `$connection->close(...)` would trigger '$connection->state->close(...)' (that could close the socket via` $connection->_close_socket()`, if necessary), change the state to`Closed` and then handling the rest of the writing queue.

**Comment by burak** [comment]
Talking about SUPER, code like this a no-op functionality wise (as it doesn't change anything just calling the parent), but adding an extra method call:

`sub new { shift->SUPER::new( @_ ); }`

and can be removed.

**Comment by chcat** [comment]
Hi Burak! I was quite sure that when you call a method on a package (like Package->new(...)) the package's ISA is not involed: that is inheritance works only for instance method calls...

**Comment by burak** [comment]
Uhm. With SUPER::new() you are picking up whatever class is on the top first (if there are multiple) and then, if there is no such method the other classes and their symbol tables will be searched and even eventual die() if there is no such method and ISA is certainly involved as that's the hierarchy registry.

https://metacpan.org/pod/distribution/perl/pod/perlobj.pod#How-SUPER-is-Resolved
https://metacpan.org/pod/distribution/perl/pod/perlobj.pod#A-Class-is-Simply-a-Package

**Comment by burak** [comment]
I'll hijack Pedro's ticket a bit more and mention something else I've noticed. There are some god objects here and there and if they are not cleaned up properly they may lead to some memory leaks or weird errors. 

eg:

`    my $cluster = HBase::Client::Cluster->new(
            meta_holder_locator => $meta_holder_locator,
            node_pool           => $node_pool,
        );
    return bless {
            cluster => $cluster,
`

I didn't run the code for real to see what it does tho

**Comment by chcat** [comment]
You got me wrong: what I mean is that I was quite sure that if you define sub "new" in the package Parent and a package Child inheriting from Parent you can't call Child->new unless you define "new" it in Child because when you call via arrow -> and the left hand side is not an instance but a package its ISA is not involved.

**Comment by burak** [comment]
Ah, no :)

So if that was true then the first one should have failed:

`:~ bgursoy$ perl -E 'package Y;sub new{bless{},shift}package X;@ISA=qw(Y); package main; my $o=X->new; say "$o"'
X=HASH(0x7fe101824ce0)
`

`
:~ bgursoy$ perl -E 'package Y;sub new{bless{},shift}package X;@ISA=qw(Y); sub new {shift->SUPER::new(@_)} package main; my $o=X->new; say "$o"'
X=HASH(0x7fdb0182daf8)
`

**Comment by burak** [comment]
+ a syntax check is worthwhile: 

https://gist.github.com/burak/2bb29a3d05161c52abff3ba060b81a97

**Comment by chcat** [comment]
Connection refactored.
